package plugin;

public interface MontiCoreException {
  enum ExceptionType {
    CLASS_NAME_MISSING, CLASSDIAGRAM_NAME_MISSING, INTERFACE_NAME_MISSING,
    ENUM_NAME_MISSING, CLASS_ATTRIBUTE_NAME_MISSING, CLASS_ATTRIBUTE_TYPE_MISSING,
    ENUM_CONSTANT_NAME_MISSING, CONSTRUCTOR_NAME_MISSING, METHOD_RETURNTYPE_MISSING,
    METHOD_NAME_MISSING, METHOD_PARAMETER_NAME_MISSING, METHOD_PARAMETER_TYPE_MISSING,
    LEFT_REFERENCE_NAME_MISSING, RIGHT_REFERENCE_NAME_MISSING
}

  String getContentMessage();
}
